// task , importance , hint , title
module.exports = [
  ['OK',0,'Message','Enemy message'],
  ['... --- ...',1,'.manual','Enemy message'],
  ['69.420,420.69',2,'Coords','Enemy message'],
  ['**Weather Report:** \ntemp:36°C \nPartly Cloudy',0,'Weather Report','Enemy message']
 , ['-.  .  -..-  -  .--  .  .  -.-',1,'.manual','Enemy message'],
  ['**Weather Report:** \ntemp:34°C \nSunny',0,'Weather Report','Friendly message'],
  ['Notice for all messages to be in morse',1,'Enemy message','Enemy message'],
  ['---  -.-',0,'.manual','Enemy message'],
  ['--  -.-  .  -  .-.  .--.  ... ',2,'.manual','Enemy message'],
  ['Soldiers, \nWe\'ve sent you transcribers to transcribe morse to letters quickly. Do your work properly for the welfare of your family. \nHail Acklana',0,'Friendly message','Friendly message'],
  ['Hail Boscha',0,'Enemy message','Enemy message'],
  ['500 Ready',1,'Enemy message','Enemy message'],
  ['**Weather Report:** \ntemp:37°C \nCloudy',0,'Weather Report','Enemy message'],
  ['Take position',2,'Enemy message','Enemy message'],
  ['.-  -  -.-  -  --  .-. .-- \n*Transcriber seems to be not working*',2,'.manual','Enemy message'],
  ['...  .-  RA .... ,\nI\'ll b  .  -...  -.  ck  aft  .  .-.  .--AR \n Yours R ---  -...  .-.  T ',0,'.manual','Enemy message'],
  ['**Weather Report:** \ntemp:37°C \nCloudy',0,'Weather Report','Enemy message'],
  ['...  .--  -...  ---  .-.  -..   .   .-.',1,'.manual','Enemy message'],
  ['MO .-.  .  EQUI  .--. --  ENT WILL  -...  .  ....  .  .-.  .  ...  ---  --- N',0,'.manual','???'],
  ['New equipements have arrived',0,'Message from capital','Friendly message'],
  ['**Weather Report:** \ntemp:37°C \nCloudy',0,'Weather Report','Enemy message'],
  ['Troop summery:\nDeaths:13\nInjured:57\nNew:77',2,'Enemy message','Enemy message'],
  ['Good Morning',0,'???','Enemy message'],
  ['Weather Report:\ntemp:imp\nCeaser ',4,'Weather Report','Enemy message'],
  ['XQQXZH FK TXOJLRQE',3,'???','Enemy message'],
  ['Troop summery:\nDeaths:33\nInjured:87\nNew:108',2,'Enemy message','Enemy message'],
  ['EXFI YLPZEX',0,'.manual','Enemy message'],
  ['PBQRM AFPQOZQFLK FK 12.45 -56.04',4,'.manual','Enemy message'],
  ['**Weather Report:** \ntemp:37°C \nCloudy',0,'Weather Report','Enemy message'],
  ['XPPXPPFKXQB QEB MOBPFABKQ',10,'.manual','Enemy message'],
  ['ELIA YLOABOP',2,'.manual','Enemy message'],
  ['HBV:YBX',3,'Ceaser','Enemy message'],
  ['32 20 21 31 21 31 26 27 32 24 27 27 23 21 26 19 19 27 27 16',0,'BEA','Enemy message'],
]